// ─── HARDCODED BACKEND DATA ────────────────────────────────────────────────

export const SPACE_TYPES = {
  DESK: "desk",
  MEETING: "meeting",
  OFFICE: "office",
};

export const SPACE_TYPE_LABELS = {
  desk: "Scrivania",
  meeting: "Sala Riunioni",
  office: "Ufficio Privato",
};

export const STATUS = {
  AVAILABLE: "available",
  MAINTENANCE: "maintenance",
  OCCUPIED: "occupied",
};

export const STATUS_LABELS = {
  available: "Disponibile",
  maintenance: "Manutenzione",
  occupied: "Occupato",
};

export const initialSpaces = [
  {
    id: 1,
    name: "Scrivania Alpha",
    type: "desk",
    capacity: 1,
    hourlyRate: 8,
    status: "available",
    floor: 1,
    amenities: ["WiFi", "Monitor"],
  },
  {
    id: 2,
    name: "Scrivania Beta",
    type: "desk",
    capacity: 1,
    hourlyRate: 8,
    status: "available",
    floor: 1,
    amenities: ["WiFi", "Monitor"],
  },
  {
    id: 3,
    name: "Scrivania Gamma",
    type: "desk",
    capacity: 1,
    hourlyRate: 10,
    status: "maintenance",
    floor: 2,
    amenities: ["WiFi", "Monitor", "Dock Station"],
  },
  {
    id: 4,
    name: "Scrivania Delta",
    type: "desk",
    capacity: 1,
    hourlyRate: 8,
    status: "available",
    floor: 1,
    amenities: ["WiFi"],
  },
  {
    id: 5,
    name: "Sala Orione",
    type: "meeting",
    capacity: 8,
    hourlyRate: 35,
    status: "available",
    floor: 1,
    amenities: ["Proiettore", "Lavagna", "VC", "WiFi"],
  },
  {
    id: 6,
    name: "Sala Vega",
    type: "meeting",
    capacity: 12,
    hourlyRate: 50,
    status: "available",
    floor: 2,
    amenities: ["Proiettore", "Lavagna", "VC", "WiFi", "Catering"],
  },
  {
    id: 7,
    name: "Sala Sirio",
    type: "meeting",
    capacity: 4,
    hourlyRate: 25,
    status: "available",
    floor: 1,
    amenities: ["TV 4K", "WiFi"],
  },
  {
    id: 8,
    name: "Sala Altair",
    type: "meeting",
    capacity: 20,
    hourlyRate: 80,
    status: "maintenance",
    floor: 3,
    amenities: ["Stage", "Proiettore", "PA System", "WiFi"],
  },
  {
    id: 9,
    name: "Ufficio Nova",
    type: "office",
    capacity: 4,
    hourlyRate: 60,
    status: "available",
    floor: 2,
    amenities: ["WiFi", "Stampante", "Locker", "Cucina"],
  },
  {
    id: 10,
    name: "Ufficio Pulsar",
    type: "office",
    capacity: 6,
    hourlyRate: 85,
    status: "available",
    floor: 3,
    amenities: ["WiFi", "Stampante", "Locker", "Cucina", "Terrazza"],
  },
  {
    id: 11,
    name: "Ufficio Quasar",
    type: "office",
    capacity: 2,
    hourlyRate: 45,
    status: "available",
    floor: 2,
    amenities: ["WiFi", "Stampante"],
  },
  {
    id: 12,
    name: "Scrivania Epsilon",
    type: "desk",
    capacity: 1,
    hourlyRate: 8,
    status: "available",
    floor: 1,
    amenities: ["WiFi"],
  },
];

// Generate past bookings for reports
const genDate = (daysAgo, h, m = 0) => {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  d.setHours(h, m, 0, 0);
  return d.toISOString();
};

export const initialBookings = [
  {
    id: "BK001",
    spaceId: 5,
    spaceName: "Sala Orione",
    spaceType: "meeting",
    customerName: "Marco Bianchi",
    date: genDate(1, 9),
    startTime: "09:00",
    endTime: "11:00",
    hours: 2,
    totalCost: 70,
    status: "confirmed",
    createdAt: genDate(3, 10),
  },
  {
    id: "BK002",
    spaceId: 1,
    spaceName: "Scrivania Alpha",
    spaceType: "desk",
    customerName: "Giulia Rossi",
    date: genDate(1, 8),
    startTime: "08:00",
    endTime: "18:00",
    hours: 10,
    totalCost: 80,
    status: "confirmed",
    createdAt: genDate(2, 14),
  },
  {
    id: "BK003",
    spaceId: 9,
    spaceName: "Ufficio Nova",
    spaceType: "office",
    customerName: "StartUp Innova Srl",
    date: genDate(2, 10),
    startTime: "10:00",
    endTime: "18:00",
    hours: 8,
    totalCost: 480,
    status: "confirmed",
    createdAt: genDate(4, 9),
  },
  {
    id: "BK004",
    spaceId: 6,
    spaceName: "Sala Vega",
    spaceType: "meeting",
    customerName: "TechCorp Italia",
    date: genDate(3, 14),
    startTime: "14:00",
    endTime: "17:00",
    hours: 3,
    totalCost: 150,
    status: "confirmed",
    createdAt: genDate(5, 11),
  },
  {
    id: "BK005",
    spaceId: 2,
    spaceName: "Scrivania Beta",
    spaceType: "desk",
    customerName: "Luca Ferrari",
    date: genDate(4, 9),
    startTime: "09:00",
    endTime: "13:00",
    hours: 4,
    totalCost: 32,
    status: "confirmed",
    createdAt: genDate(6, 8),
  },
  {
    id: "BK006",
    spaceId: 10,
    spaceName: "Ufficio Pulsar",
    spaceType: "office",
    customerName: "Design Studio MV",
    date: genDate(5, 9),
    startTime: "09:00",
    endTime: "18:00",
    hours: 9,
    totalCost: 765,
    status: "confirmed",
    createdAt: genDate(7, 15),
  },
  {
    id: "BK007",
    spaceId: 7,
    spaceName: "Sala Sirio",
    spaceType: "meeting",
    customerName: "Anna Conti",
    date: genDate(6, 11),
    startTime: "11:00",
    endTime: "13:00",
    hours: 2,
    totalCost: 50,
    status: "confirmed",
    createdAt: genDate(8, 9),
  },
  {
    id: "BK008",
    spaceId: 5,
    spaceName: "Sala Orione",
    spaceType: "meeting",
    customerName: "Nexus Group",
    date: genDate(7, 15),
    startTime: "15:00",
    endTime: "18:00",
    hours: 3,
    totalCost: 105,
    status: "confirmed",
    createdAt: genDate(9, 10),
  },
  {
    id: "BK009",
    spaceId: 4,
    spaceName: "Scrivania Delta",
    spaceType: "desk",
    customerName: "Roberto Esposito",
    date: genDate(8, 8),
    startTime: "08:00",
    endTime: "20:00",
    hours: 12,
    totalCost: 96,
    status: "confirmed",
    createdAt: genDate(10, 7),
  },
  {
    id: "BK010",
    spaceId: 9,
    spaceName: "Ufficio Nova",
    spaceType: "office",
    customerName: "Freelance Hub",
    date: genDate(9, 9),
    startTime: "09:00",
    endTime: "17:00",
    hours: 8,
    totalCost: 480,
    status: "confirmed",
    createdAt: genDate(11, 12),
  },
  {
    id: "BK011",
    spaceId: 6,
    spaceName: "Sala Vega",
    spaceType: "meeting",
    customerName: "Medico Assoc.",
    date: genDate(10, 13),
    startTime: "13:00",
    endTime: "16:00",
    hours: 3,
    totalCost: 150,
    status: "confirmed",
    createdAt: genDate(12, 8),
  },
  {
    id: "BK012",
    spaceId: 11,
    spaceName: "Ufficio Quasar",
    spaceType: "office",
    customerName: "Sara Mancini",
    date: genDate(11, 10),
    startTime: "10:00",
    endTime: "16:00",
    hours: 6,
    totalCost: 270,
    status: "confirmed",
    createdAt: genDate(13, 9),
  },
  {
    id: "BK013",
    spaceId: 1,
    spaceName: "Scrivania Alpha",
    spaceType: "desk",
    customerName: "Paolo Greco",
    date: genDate(12, 9),
    startTime: "09:00",
    endTime: "18:00",
    hours: 9,
    totalCost: 72,
    status: "confirmed",
    createdAt: genDate(14, 10),
  },
  {
    id: "BK014",
    spaceId: 5,
    spaceName: "Sala Orione",
    spaceType: "meeting",
    customerName: "Agenzia Creativa",
    date: genDate(13, 10),
    startTime: "10:00",
    endTime: "12:00",
    hours: 2,
    totalCost: 70,
    status: "confirmed",
    createdAt: genDate(15, 11),
  },
  {
    id: "BK015",
    spaceId: 10,
    spaceName: "Ufficio Pulsar",
    spaceType: "office",
    customerName: "Venture Lab",
    date: genDate(14, 9),
    startTime: "09:00",
    endTime: "18:00",
    hours: 9,
    totalCost: 765,
    status: "confirmed",
    createdAt: genDate(16, 9),
  },
  {
    id: "BK016",
    spaceId: 2,
    spaceName: "Scrivania Beta",
    spaceType: "desk",
    customerName: "Elena Bruno",
    date: genDate(15, 8),
    startTime: "08:00",
    endTime: "14:00",
    hours: 6,
    totalCost: 48,
    status: "confirmed",
    createdAt: genDate(17, 8),
  },
  {
    id: "BK017",
    spaceId: 7,
    spaceName: "Sala Sirio",
    spaceType: "meeting",
    customerName: "Startup Week",
    date: genDate(16, 14),
    startTime: "14:00",
    endTime: "17:00",
    hours: 3,
    totalCost: 75,
    status: "confirmed",
    createdAt: genDate(18, 13),
  },
  {
    id: "BK018",
    spaceId: 9,
    spaceName: "Ufficio Nova",
    spaceType: "office",
    customerName: "Digital Agency",
    date: genDate(17, 9),
    startTime: "09:00",
    endTime: "18:00",
    hours: 9,
    totalCost: 540,
    status: "confirmed",
    createdAt: genDate(19, 9),
  },
  {
    id: "BK019",
    spaceId: 12,
    spaceName: "Scrivania Epsilon",
    spaceType: "desk",
    customerName: "Marco Rizzo",
    date: genDate(18, 9),
    startTime: "09:00",
    endTime: "17:00",
    hours: 8,
    totalCost: 64,
    status: "confirmed",
    createdAt: genDate(20, 10),
  },
  {
    id: "BK020",
    spaceId: 6,
    spaceName: "Sala Vega",
    spaceType: "meeting",
    customerName: "Corporate Event",
    date: genDate(20, 9),
    startTime: "09:00",
    endTime: "18:00",
    hours: 9,
    totalCost: 450,
    status: "confirmed",
    createdAt: genDate(22, 9),
  },
];
